services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./newApp:/var/www/html
    ports:
      - 8000:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=TfgTester
      - DB_USERNAME=user
      - DB_PASSWORD=
  
  mysql:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      - MARIADB_DATABASE=TfgTester
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - UPLOAD_LIMIT=1G
    depends_on:
      - mysql
   